artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/imayank45/Chicken-Disease-Classification/raw/refs/heads/main/Chicken-fecal-image-dataset.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion